spring:
  datasource:
    url: jdbc:h2:file:C:/Users/antho/eclipse-workspace151/CrissX/testdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect